### ISSUE TITLE
"sdk" is too generic of a name

### ISSUE THREAD

**Issue by jhorvat** [MAXAds/max-android-sdk#2]
Hey guys, going through the integration process and I think that the "sdk" module's name is way too generic. Would it be possible to rename the module folder to something like ```max-android-sdk``` so that end consumers can more easily tell what the module is?

**Comment by steffanc** [comment]
Hi, the module is being renamed to max-sdk and will be updated in the next release

**Comment by jhorvat** [comment]
@steffanc good to hear 😄
