### ISSUE TITLE
There's no sdk folder in 0.6.0

### ISSUE THREAD

**Issue by proevan** [MAXAds/max-android-sdk#4]
There's no sdk folder in 0.6.0

**Comment by steffanc** [comment]
The sdk folder has been renamed to max-sdk. Is this causing you any issues?

**Comment by proevan** [comment]
it needs to comment out apply from: 'install.gradle' and apply from: 'bintray.gradle'

**Comment by steffanc** [comment]
Can you explain further? Are these lines causing you issues on your end?

**Comment by proevan** [comment]
since that's the settings for uploading to bintray. 
But as an user, if we don't comment out these two lines in the app build.gradle:
apply from: 'install.gradle'
apply from: 'bintray.gradle'
then we will need to add these two dependencies in project build.gradle file:
classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.0'
lasspath 'com.github.dcendents:android-maven-gradle-plugin:2.0'

**Comment by steffanc** [comment]
This has been fixed in 0.7.1
